// <auto-generated />
using System;
using CASHKY.YarnSystem.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CASHKY.YarnSystem.Migrations
{
    [DbContext(typeof(YarnDbContext))]
    [Migration("20231228133914_db1")]
    partial class db1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CASHKY.YarnSystem.YarnCategory.YarnCategoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("yarn.categories");
                });

            modelBuilder.Entity("CASHKY.YarnSystem.YarnWarehousing.YarnWarehousingEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Batch")
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InventoryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remarks")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<long>("YarnCategoryId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("YarnCategoryId");

                    b.ToTable("yarn.warehousing");
                });

            modelBuilder.Entity("CASHKY.YarnSystem.YarnWarehousing.YarnWarehousingEntity", b =>
                {
                    b.HasOne("CASHKY.YarnSystem.YarnCategory.YarnCategoryEntity", "YarnCategory")
                        .WithMany("YarnWarehousings")
                        .HasForeignKey("YarnCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("YarnCategory");
                });

            modelBuilder.Entity("CASHKY.YarnSystem.YarnCategory.YarnCategoryEntity", b =>
                {
                    b.Navigation("YarnWarehousings");
                });
#pragma warning restore 612, 618
        }
    }
}
